In [4]:
import pandas as pd
import numpy as np

In [202]:
highofficer = pd.read_csv('C:\\GitHub\\test\\highofficer_2019.csv', encoding = 'cp949')
highofficer.head()

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,소재지 면적 등 권리의 명세,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years
0,1,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,경상남도 양산시 매곡동 28번지 159.00㎡,"20,177.0",0.0,0.0,0.0,0.0,"20,177.0",공시지가 변동없음,2018
1,2,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,경상남도 양산시 매곡동 29번지 577.00㎡,"73,221.0",0.0,0.0,0.0,0.0,"73,221.0",공시지가 변동없음,2018
2,3,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-2번지 15.00㎡,340.0,0.0,0.0,0.0,0.0,340.0,공시지가 변동없음,2018
3,4,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-3번지 14.00㎡,317.0,0.0,0.0,0.0,0.0,317.0,공시지가 변동없음,2018
4,5,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-4번지 47.00㎡,"1,066.0",0.0,0.0,0.0,0.0,"1,066.0",공시지가 변동없음,2018

In [203]:
highofficer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86174 entries, 0 to 86173
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       86174 non-null  int64
 1   소속_대분류           86174 non-null  object
 2   소속_소분류           86174 non-null  object
 3   소속               86174 non-null  object
 4   직위               85174 non-null  object
 5   성명               86174 non-null  object
 6   개별index          86174 non-null  object
 7   대분류              86174 non-null  object
 8   본인과의 관계          86174 non-null  object
 9   재산의 종류           70561 non-null  object
 10  소재지 면적 등 권리의 명세  85302 non-null  object
 11  종전가액             86174 non-null  float64
 12  증가액              86174 non-null  float64
 13  증가액_실거래가         86174 non-null  float64
 14  감소액              86174 non-null  float64
 15  감소액_실거래가         86174 non-null  float64
 16  현재가액             86174 non-null  float64
 17  변동사유             77151 non-null  object
 18  years            86174 non-null  int64
dtypes: float64(6), int64(2), object(11)
memory usage: 12.5+ MB

In [204]:
highofficer[highofficer['대분류'] == '건물']['재산의 종류'].unique()

array(['단독주택', '근린생활시설', '연립주택', '오피스텔전세(임차)권', '아파트', '아파트전세(임차)권',
       '다세대주택', '상가', '연립주택전세(임차)권', '근린생활시설전세(임차)권', '복합건물(주택+상가)',
       '아파트(분양권)', '사무실전세(임차)권', '오피스텔', '상가전세(임차)권', '자동차관련시설', '기타',
       '기타전세(임차)권', '사무실', '공장', '다세대주택전세(임차)권', '다가구주택', '단독주택전세(임차)권',
       '빌딩', '빌딩전세(임차)권', '복합건물(주택+상가)전세(임차)권', '창고', '사무실(분양권)',
       '의료시설전세(임차)권', '다가구주택전세(임차)권', '오피스텔(분양권)', '숙박시설(분양권)', '숙박시설',
       '상가(분양권)', '교육연구및복지시설', '연립주택(분양권)', '위락시설(분양권)', '기숙사전세(임차)권',
       '기숙사', '묘지관련시설', '공장전세(임차)권', '운동시설전세(임차)권', '창고전세(임차)권',
       '복합건물(주택+상가)(분양권)', nan, '위락시설', '교육연구및복지시설전세(임차)권', '기타건물',
       '단독주택,경량철골조', '주유(충전)소', '의료시설', '근린생활시설(분양권)', '휴게소전세(임차)권',
       '운동시설', '단독주택(분양권)', '기타(분양권)', '전세(임차)권', '주택겸근린생활시설', '농업생산시설',
       '업무시설', '업무시설및근린생활시설', '식품위생시설', '차량관리시설', '농어가주택', '체육시설',
       '근린생활시설및주택', '축사', '근린생활시설및업무시설', '복합건물', '숙박시설전세(임차)권', '문화및집회시설',
       '다세대주택(분양권)', '주택'], dtype=object)

In [205]:
highofficer_apt = highofficer[highofficer['재산의 종류'].isin(['아파트', '아파트전세(임차)권', '아파트(분양권)'])]
highofficer_apt

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,소재지 면적 등 권리의 명세,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years
15,16,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,건물,모,아파트,부산광역시 영도구 남항동3가 남항화랑멘션 건물 83.16㎡,"127,000.0",0.0,0.0,0.0,0.0,"127,000.0",가액변동 없음,2018
35,36,청와대,청와대,대통령비서실,대통령비서실장,임종석,대통령비서실-대통령비서실장-임종석,건물,배우자,아파트,서울특별시 은평구 진관동 은평뉴타운 마고정 건물 101.83㎡,"444,000.0",0.0,0.0,0.0,0.0,"444,000.0",가액변동 없음,2018
86,87,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,본인,아파트,서울특별시 송파구 잠실동 아시아선수촌 건물 134.48㎡ 중 67.24㎡,"552,000.0","76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018
88,89,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,배우자,아파트,서울특별시 송파구 잠실동 아시아선수촌 건물 134.48㎡ 중 67.24㎡,"552,000.0","76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018
89,90,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,장남,아파트전세(임차)권,"COMMERCE DR NW, ATLANTA, GA 30318 건물 49.50㎡","2,953.0",0.0,0.0,0.0,0.0,"2,953.0",NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86123,86124,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,아파트전세(임차)권,부산광역시 남구 대연동 건물 46.27㎡,"150,000.0",0.0,0.0,0.0,0.0,"150,000.0",변동없음,2019
86146,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,서울특별시 서대문구 북가좌동 건물 84.33㎡,"236,000.0","28,000.0",0.0,0.0,0.0,"264,000.0",가액변동,2019
86158,86159,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트,서울특별시 강남구 개포동 건물 36.00㎡ 중 18.00㎡,"256,500.0","40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019
86159,86160,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트전세(임차)권,서울특별시 강남구 대치동 건물 77.00㎡,"430,000.0",0.0,0.0,0.0,0.0,"430,000.0",변동없음,2019
86161,86162,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,배우자,아파트,서울특별시 강남구 개포동 건물 36.00㎡ 중 18.00㎡,"256,500.0","40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019

In [206]:
real_estate_count = real_estate.groupby(['성명', 'years'])['재산의 종류'].count()
real_estate_count
real_estate_count.to_excel('C:\\GitHub\\test\\real_estate_count.xlsx')

In [207]:
highofficer_apt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8002 entries, 15 to 86161
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       8002 non-null   int64
 1   소속_대분류           8002 non-null   object
 2   소속_소분류           8002 non-null   object
 3   소속               8002 non-null   object
 4   직위               7892 non-null   object
 5   성명               8002 non-null   object
 6   개별index          8002 non-null   object
 7   대분류              8002 non-null   object
 8   본인과의 관계          8002 non-null   object
 9   재산의 종류           8002 non-null   object
 10  소재지 면적 등 권리의 명세  7999 non-null   object
 11  종전가액             8002 non-null   float64
 12  증가액              8002 non-null   float64
 13  증가액_실거래가         8002 non-null   float64
 14  감소액              8002 non-null   float64
 15  감소액_실거래가         8002 non-null   float64
 16  현재가액             8002 non-null   float64
 17  변동사유             7184 non-null   object
 18  years            8002 non-null   int64
dtypes: float64(6), int64(2), object(11)
memory usage: 1.2+ MB

In [230]:
area = highofficer_apt['소재지 면적 등 권리의 명세'].str.split(' ').str[0]
highofficer_apt['광역시'] = area
area_detail = highofficer_apt['소재지 면적 등 권리의 명세'].str.split(' ').str[1]
highofficer_apt['구'] = area_detail
highofficer_apt

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years,광역시,구
15,16,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,건물,모,아파트,...,"127,000.0",0.0,0.0,0.0,0.0,"127,000.0",가액변동 없음,2018,부산광역시,영도구
35,36,청와대,청와대,대통령비서실,대통령비서실장,임종석,대통령비서실-대통령비서실장-임종석,건물,배우자,아파트,...,"444,000.0",0.0,0.0,0.0,0.0,"444,000.0",가액변동 없음,2018,서울특별시,은평구
86,87,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,본인,아파트,...,"552,000.0","76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018,서울특별시,송파구
88,89,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,배우자,아파트,...,"552,000.0","76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018,서울특별시,송파구
89,90,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,장남,아파트전세(임차)권,...,"2,953.0",0.0,0.0,0.0,0.0,"2,953.0",NaN,2018,COMMERCE,DR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86123,86124,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,아파트전세(임차)권,...,"150,000.0",0.0,0.0,0.0,0.0,"150,000.0",변동없음,2019,부산광역시,남구
86146,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,"236,000.0","28,000.0",0.0,0.0,0.0,"264,000.0",가액변동,2019,서울특별시,서대문구
86158,86159,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트,...,"256,500.0","40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019,서울특별시,강남구
86159,86160,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트전세(임차)권,...,"430,000.0",0.0,0.0,0.0,0.0,"430,000.0",변동없음,2019,서울특별시,강남구
86161,86162,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,배우자,아파트,...,"256,500.0","40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019,서울특별시,강남구

In [235]:
highofficer_apt['광역시'] = highofficer_apt['광역시'].fillna('없음')
highofficer_apt['구'] = highofficer_apt['구'].fillna('없음')

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [233]:
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('서울|소재지',case=False),'광역시']='서울'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('강원',case=False),'광역시']='강원'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('부산',case=False),'광역시']='부산'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('경기|오산',case=False),'광역시']='경기'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('대구',case=False),'광역시']='대구'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('충청',case=False),'광역시']='충청'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('인천',case=False),'광역시']='인천'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('대전',case=False),'광역시']='대전'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('전라|군산',case=False),'광역시']='전라'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('광주',case=False),'광역시']='광주'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('울산',case=False),'광역시']='울산'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('경상',case=False),'광역시']='경상'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('세종|행정',case=False),'광역시']='세종'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('제주',case=False),'광역시']='제주'
highofficer_apt.loc[highofficer_apt['광역시'].str.contains('미국|동경|H|w|C|B|중국',case=False),'광역시']='해외'

C:\Users\sds\anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [237]:
highofficer_apt['광역시'].unique()

array(['부산', '서울', '해외', '경기', '충청', '전라', '인천', '세종', '강원', '울산', '없음',
       '대구', '경상', '광주', '제주', '대전', '전남', '경남', '경북', '전북', '충북'],
      dtype=object)

In [249]:
highofficer_apt.loc[highofficer_apt['구'].str.contains('종로구',case=False),'구_서울']='종로구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('중구',case=False),'구_서울']='중구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('용산구',case=False),'구_서울']='용산구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('성동구',case=False),'구_서울']='성동구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('광진구',case=False),'구_서울']='광진구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('동대문구',case=False),'구_서울']='동대문구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('중랑구',case=False),'구_서울']='중랑구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('성북구',case=False),'구_서울']='성북구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('강북구',case=False),'구_서울']='강북구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('도봉구',case=False),'구_서울']='도봉구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('노원구',case=False),'구_서울']='노원구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('은평구',case=False),'구_서울']='은평구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('서대문구',case=False),'구_서울']='서대문구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('마포구',case=False),'구_서울']='마포구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('양천구',case=False),'구_서울']='양천구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('강서구',case=False),'구_서울']='강서구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('구로구',case=False),'구_서울']='구로구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('금천구',case=False),'구_서울']='금천구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('영등포구',case=False),'구_서울']='영등포구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('동작구',case=False),'구_서울']='동작구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('관악구',case=False),'구_서울']='관악구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('서초구',case=False),'구_서울']='서초구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('강남구',case=False),'구_서울']='강남구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('송파구',case=False),'구_서울']='송파구'
highofficer_apt.loc[highofficer_apt['구'].str.contains('강동구',case=False),'구_서울']='강동구'

In [258]:
highofficer_apt['구_서울'] = np.where((highofficer_apt['광역시'] == '서울') & (highofficer_apt['구_서울'].isnull()), '서울 기타', highofficer_apt['구_서울'])

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [268]:
highofficer_apt['구_서울'] = highofficer_apt['구_서울'].fillna('서울 아님')

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [269]:
highofficer_apt['구_서울'].unique()

array(['서울 아님', '은평구', '송파구', '서울 기타', '중구', '강서구', '강남구', '서초구', '노원구',
       '성북구', '강동구', '동작구', '종로구', '관악구', '영등포구', '서대문구', '광진구', '용산구',
       '마포구', '중랑구', '양천구', '동대문구', '성동구', '강북구', '도봉구', '구로구', '금천구'],
      dtype=object)

In [273]:
highofficer_apt

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years,광역시,구,구_서울
15,16,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,건물,모,아파트,...,0.0,0.0,0.0,0.0,"127,000.0",가액변동 없음,2018,부산,영도구,서울 아님
35,36,청와대,청와대,대통령비서실,대통령비서실장,임종석,대통령비서실-대통령비서실장-임종석,건물,배우자,아파트,...,0.0,0.0,0.0,0.0,"444,000.0",가액변동 없음,2018,서울,은평구,은평구
86,87,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,본인,아파트,...,"76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018,서울,송파구,송파구
88,89,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,배우자,아파트,...,"76,000.0",0.0,0.0,0.0,"628,000.0",공시가격 변동,2018,서울,송파구,송파구
89,90,청와대,청와대,대통령비서실,정책실장,장하성,대통령비서실-정책실장-장하성,건물,장남,아파트전세(임차)권,...,0.0,0.0,0.0,0.0,"2,953.0",NaN,2018,해외,DR,서울 아님
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86123,86124,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,아파트전세(임차)권,...,0.0,0.0,0.0,0.0,"150,000.0",변동없음,2019,부산,남구,서울 아님
86146,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,"28,000.0",0.0,0.0,0.0,"264,000.0",가액변동,2019,서울,서대문구,서대문구
86158,86159,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트,...,"40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019,서울,강남구,강남구
86159,86160,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,본인,아파트전세(임차)권,...,0.0,0.0,0.0,0.0,"430,000.0",변동없음,2019,서울,강남구,강남구
86161,86162,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,건물,배우자,아파트,...,"40,500.0",0.0,0.0,0.0,"297,000.0",가액변동,2019,서울,강남구,강남구

In [280]:
apt_area = highofficer_apt.groupby(['광역시'])['소재지 면적 등 권리의 명세'].count().reset_index()
apt_area

   광역시  소재지 면적 등 권리의 명세
0   강원              199
1   경기             1484
2   경남                1
3   경북                2
4   경상              415
5   광주              226
6   대구              246
7   대전              201
8   부산              371
9   서울             3434
10  세종              315
11  없음                0
12  울산               86
13  인천              248
14  전남                1
15  전라              372
16  전북                2
17  제주               55
18  충북                2
19  충청              327
20  해외               12

In [276]:
apt_seoul =  highofficer_apt.groupby(['구_서울'])['소재지 면적 등 권리의 명세'].count().reset_index()
apt_seoul

     구_서울  소재지 면적 등 권리의 명세
0     강남구              654
1     강동구               97
2     강북구               16
3     강서구               95
4     관악구               52
5     광진구               51
6     구로구               37
7     금천구               16
8     노원구               80
9     도봉구               43
10   동대문구               45
11    동작구              121
12    마포구              137
13   서대문구               89
14  서울 기타              187
15  서울 아님             4498
16    서초구              637
17    성동구              109
18    성북구               68
19    송파구              283
20    양천구              101
21   영등포구              121
22    용산구              198
23    은평구               52
24    종로구               64
25     중구              110
26    중랑구               38

In [282]:
highofficer_apt.to_excel('C:\\GitHub\\test\\highofficer_apt.xlsx')

In [284]:
apt_area.to_excel('C:\\GitHub\\test\\highofficer_apt_area.xlsx')

In [285]:
apt_seoul.to_excel('C:\\GitHub\\test\\highofficer_apt_seoul.xlsx')

In [310]:
highofficer_2019 = highofficer[(highofficer['years'] == 2019) & (highofficer['대분류'] != '채무')]
highofficer_2019

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,소재지 면적 등 권리의 명세,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years
42447,42448,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,경상남도 양산시 매곡동 28번지 159.00㎡,"20,177.0","3,736.0",0.0,0.0,0.0,"23,913.0",공시지가 변동,2019
42448,42449,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,경상남도 양산시 매곡동 29번지 577.00㎡,"73,221.0","13,559.0",0.0,0.0,0.0,"86,780.0",공시지가 변동,2019
42449,42450,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-2번지 15.00㎡,340.0,15.0,0.0,0.0,0.0,355.0,공시지가 변동,2019
42450,42451,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-3번지 14.00㎡,317.0,14.0,0.0,0.0,0.0,331.0,공시지가 변동,2019
42451,42452,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-4번지 47.00㎡,"1,066.0",47.0,0.0,0.0,0.0,"1,113.0",공시지가 변동,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86165,86166,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기,본인,자동차,"2014년식 그랜저 배기량(24,000cc)","20,160.0",0.0,0.0,"1,480.0",0.0,"18,680.0",가액변동,2019
86166,86167,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,예금,본인,NaN,"신영증권 235,479(43,8 03 감소), 우리은행 2,179(1,095 증가)...","305,382.0","18,001.0",0.0,"43,803.0",0.0,"279,580.0",펀드 손실,2019
86167,86168,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,예금,배우자,NaN,"수협은행 3, 국민은행 11,657(2,917 증가), 우체국 25,160(3,40...","75,503.0","51,370.0",0.0,"45,000.0",0.0,"81,873.0",펀드 손실,2019
86172,86173,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,고지거부및등록제외사항,부,NaN,고지거부,0.0,0.0,0.0,0.0,0.0,0.0,독립생계유지,2019
86173,86174,사법부,사법부,헌법재판소,기획조정실장,김용호,헌법재판소-기획조정실장-김용호,고지거부및등록제외사항,모,NaN,고지거부,0.0,0.0,0.0,0.0,0.0,0.0,독립생계유지,2019

In [311]:
highofficer_rich_family = highofficer_2019.groupby(['성명', '본인과의 관계'])['현재가액'].sum().reset_index()
highofficer_rich_own = highofficer_rich_family[highofficer_rich_family['본인과의 관계'] == '본인']
highofficer_rich_own

        성명 본인과의 관계        현재가액
1      가세로      본인 1,493,958.0
5      강경구      본인 1,096,840.0
10     강경화      본인 1,184,106.0
16     강근식      본인   254,770.0
22     강길부      본인 3,544,414.0
...    ...     ...         ...
10600  황철규      본인   783,850.0
10606  황치영      본인 1,343,802.0
10611  황한식      본인 2,208,603.0
10614  황현택      본인   116,758.0
10618   황희      본인   177,024.0

[2292 rows x 3 columns]

In [312]:
highofficer_rich_own.to_excel('C:\\GitHub\\test\\highofficer_rich_2019_own.xlsx')

In [323]:
highofficer_rich = highofficer_2019.groupby(['성명', 'years'])['현재가액'].sum().reset_index()
highofficer_rich

       성명  years        현재가액
0     가세로   2019 1,642,807.0
1     강경구   2019 2,188,270.0
2     강경화   2019 3,676,207.0
3     강근식   2019 1,010,711.0
4     강길부   2019 4,821,822.0
...   ...    ...         ...
2287  황철규   2019 1,546,771.0
2288  황치영   2019 3,038,818.0
2289  황한식   2019 4,397,501.0
2290  황현택   2019 1,741,516.0
2291   황희   2019   610,284.0

[2292 rows x 3 columns]

In [324]:
pd.options.display.float_format = '{:,}'.format
highofficer_rich = highofficer_rich.sort_values(['현재가액', 'years'], ascending = False)
highofficer_rich

       성명  years          현재가액
263   김병관   2019 276,363,061.0
336   김세연   2019 105,082,167.0
768   박덕흠   2019  53,214,676.0
867    박정   2019  45,635,990.0
2065  최교일   2019  25,954,895.0
...   ...    ...           ...
514   김진석   2019      21,565.0
179   김광모   2019      13,623.0
2105  최영아   2019       8,245.0
1203   여명   2019       6,171.0
378   김영수   2019       3,668.0

[2292 rows x 3 columns]

In [325]:
highofficer_rich_2019 = highofficer_rich[highofficer_rich['years'] == 2019]
highofficer_rich_2019

       성명  years          현재가액
263   김병관   2019 276,363,061.0
336   김세연   2019 105,082,167.0
768   박덕흠   2019  53,214,676.0
867    박정   2019  45,635,990.0
2065  최교일   2019  25,954,895.0
...   ...    ...           ...
514   김진석   2019      21,565.0
179   김광모   2019      13,623.0
2105  최영아   2019       8,245.0
1203   여명   2019       6,171.0
378   김영수   2019       3,668.0

[2292 rows x 3 columns]

In [328]:
highofficer_rich_2019_portion = pd.merge(highofficer_rich_2019, highofficer_rich_own, left_on = '성명', right_on = '성명')
highofficer_rich_2019_portion

       성명  years        현재가액_x 본인과의 관계        현재가액_y
0     김병관   2019 276,363,061.0      본인 259,500,374.0
1     김세연   2019 105,082,167.0      본인 104,770,092.0
2     박덕흠   2019  53,214,676.0      본인  33,317,071.0
3      박정   2019  45,635,990.0      본인  40,776,845.0
4     최교일   2019  25,954,895.0      본인   4,143,579.0
...   ...    ...           ...     ...           ...
2287  김진석   2019      21,565.0      본인      21,565.0
2288  김광모   2019      13,623.0      본인      12,557.0
2289  최영아   2019       8,245.0      본인       2,331.0
2290   여명   2019       6,171.0      본인       6,171.0
2291  김영수   2019       3,668.0      본인       3,668.0

[2292 rows x 5 columns]

In [329]:
highofficer_rich_2019_portion.to_excel('C:\\GitHub\\test\\highofficer_rich_2019_portion.xlsx')

In [327]:
highofficer_rich_2019.to_excel('C:\\GitHub\\test\\highofficer_rich_2019.xlsx')

In [320]:
site = highofficer['소재지 면적 등 권리의 명세'].fillna('없음')

In [321]:
highofficer['소재지_re'] = site

In [322]:
seongdong_gu = highofficer[highofficer['소재지_re'].str.contains('성동구')]
seongdong_gu['소재지_re'].values

array(['서울특별시성동구금호동3가 두산아파트건물59.97㎡',
       '서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡',
       '서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡',
       '서울특별시 성동구 성수동2가 342-10번지 10.00㎡ 중 1.66㎡',
       '서울특별시 성동구 성수동2가 342-6번지 0.00㎡ 중 0.00㎡',
       '서울특별시 성동구 성수동2가 건물 149.00㎡ 중 24.83㎡',
       '서울특별시 성동구 금호동3가 두산아파트 건물 145.16㎡중 72.58㎡',
       '서울특별시성동구금호동3가 두산아파트건물72.58㎡', '서울특별시 성동구 옥수동 옥수파크힐스아파트 건물115.90㎡',
       '서울특별시 성동구 성수동1가 668-23번지 221.00㎡ 중 49.11㎡',
       '서울특별시 성동구 옥수동 더 어울림 아파트 건물 84.69㎡',
       '서울특별시 성동구 용답동 아원산업 대지 1.30㎡ 건물 9.60㎡',
       '서울특별시 성동구 용답동 아원산업 임대보증금 증가', '서울특별시 성동구 금호동3가 두산아파트 건물 59.97㎡',
       '서울특별시 성동구 옥수동 한남하이츠아파트 건물 177.16㎡',
       '서울특별시 성동구 행당동 행당한진타운 건물 84.00㎡', '서울특별시 성동구 행당동 행당한진타운 임대보증금',
       '서울특별시 성동구 성수동2가 성수동아이파크 건물 84.98㎡',
       '서울특별시 성동구 옥수동 옥수하이츠 아파트 건물 114.78㎡',
       '서울특별시 성동구 옥수동 옥수하이츠 아파트 임대보증금 증가',
       '서울특별시 성동구 성수동2가 강변임광아파트 건물 59.67㎡',
       '서울특별시 성동구 금호동3가 두산아파트 건물 59.97㎡', '서울특별시 성동구 행당동 대림아파트 건물 84.87㎡',
       '서울특별시 성동구 행당동 한진타운 건물 114.62㎡', '서울특별시 성동구 행당동 한진타운 임대보증금',
       '서울 성동구 무학로 건물 6.00㎡', '서울특별시 성동구 옥수동 극동그린아파트 건물 102.00㎡',
       '서울특별시 성동구 행당동 행당대림아파트 건물 114.62㎡',
       '서울특별시성동구행당동 행당대림아파트건물11,544.12㎡중114.94㎡',
       '서울특별시 성동구 행당동 행당동한진아파트 건물 114.62㎡ 중57.31㎡',
       '서울특별시성동구행당동 행당동한진아파트건물114.62㎡중57.31㎡',
       '서울특별시 성동구 행당동 행당한진타운아파트 건물144.00㎡ 중 72.00㎡',
       '서울특별시 성동구 행당동 행당한진타운아파트 건물144.00㎡ 중 72.00㎡',
       '서울특별시 성동구 행당동 행당한진타운아파트 임대보증금증가',
       '서울특별시 성동구 행당동 행당한진타운아파트 임대보증금증가', '서울특별시성동구마장동 금호어울림아파트건물84.0 ㎡',
       '서울특별시 성동구 사근동 건물 132.36㎡', '서울특별시 성동구 하왕십리동 금호베스트빌 건물 114.93㎡',
       '서울특별시 성동구 하왕십리동 왕십리자이아파트 건물59.99㎡',
       '서울특별시 성동구 금호동4가 서울숲푸르지오아파트 건물0.00㎡',
       '서울특별시성동구하왕십리동 센트라스건물115.99㎡',
       '서울특별시 성동구 행당동 대지 249.66㎡ 건물 306.00㎡',
       '서울특별시 성동구 마장동 현대아파트 건물 108.00㎡', '서울특별시 성동구 금호동3가 건물 561.75㎡',
       '서울특별시 성동구 금호동4가 건물 115.62㎡', '서울특별시 성동구 금호동3가 임대보증금',
       '서울특별시 성동구 금호동4가 임대보증금',
       '서울특별시 성동구 성수동2가 성원상떼뷰오피스텔 건물3,065.50㎡ 중 8.29㎡',
       '서울특별시 성동구 행당1동 삼부아파트 건물 84.09㎡',
       '서울특별시 성동구 옥수동 래미안옥수리버젠 건물 59.25㎡', '서울특별시 성동구 성수동1가 건물 34.59㎡',
       '서울특별시 성동구 용답동 서희스타힐스리버파크 대지2,118.20㎡ 중 21.90㎡ 건물 2,118.20㎡ 중 21.90㎡',
       '서울특별시 성동구 왕십리2동 풍림아파트 건물 143.86㎡중 65.04㎡',
       '서울특별시 성동구 왕십리2동 풍림아파트 건물 143.86㎡중 64.78㎡',
       '서울특별시 성동구 왕십리2동 풍림아파트 건물 143.86㎡중 4.68㎡',
       '서울특별시 성동구 왕십리2동 풍림아파트 건물 143.86㎡중 4.68㎡',
       '서울특별시 성동구 왕십리2동 풍림아파트 건물 143.86㎡중 4.68㎡',
       '서울특별시 성동구 응봉동 대림강변타운 건물 59.76㎡',
       '서울특별시성동구상왕십리동 대지0.00㎡중0.00㎡건물0.00㎡중0.00㎡',
       '서울특별시 성동구 하왕십리동 한신무학아파트 건물 97.00㎡',
       '서울특별시 성동구 성수동1가 서울숲 벨라듀 건물84.00㎡',
       '서울특별시 성동구 성수동2가 강변현대아파트 건물 81.80㎡',
       '서울특별시 성동구 금호동2가 신금호파크자이아파트 건물79.95㎡',
       '서울특별시 성동구 금호동4가 서울숲 푸르지오 1차 건물0.00㎡',
       '서울특별시 성동구 성수동2가 건물 77.72㎡ 중 38.86㎡',
       '서울특별시 성동구 용답동 102-23번지 189.70㎡ 중 2.34㎡',
       '서울특별시 성동구 용답동 102-24번지 142.20㎡ 중 1.76㎡',
       '서울특별시 성동구 용답동 103-4번지 95.20㎡ 중 1.17㎡',
       '서울특별시 성동구 용답동 104-19번지 307.30㎡ 중 3.80㎡',
       '서울특별시 성동구 성수동2가 건물 0.00㎡', '서울 성동구 성수동2가 0㎡', '서울 성동구 성수동2가 0㎡',
       '서울 성동구 성수동2가 아파트 임대보증금 감소', '서울 성동구 성수동2가 아파트 임대보증금 감소',
       '서울성동구금호동1가114.57㎡', '서울 성동구 응봉동 84.42㎡', '서울 성동구 행당동 건물 29.43㎡',
       '서울 성동구 도선동 건물 38.58㎡', '서울 성동구 행당동 오피스텔 임대보증금 증가',
       '서울 성동구 도선동 오피스텔 임대보증금 증가', '서울 성동구 행당동 84.87㎡',
       '서울 성동구 행당동 아파트 임대보증금', '서울 성동구 금호동4가 아파트 84.838㎡',
       '서울 성동구 금호동3가 116.81㎡', '서울특별시 성동구 성수동1가 건물 164.86㎡',
       '서울특별시 성동구 옥수동  래미안 옥수 리버젠 건물 59.25㎡',
       '서울특별시 성동구 성수동2가  성원상떼뷰 건물 0.00㎡',
       '서울특별시 성동구 도선동  신한넥스텔 대지 2.56㎡ 건물19.63㎡',
       '서울특별시 성동구 도선동 신한넥스텔 임대보증금 증가',
       '서울특별시 성동구 성수동2가  램킨 중흥S-클래스 오피스텔대지 8.45㎡ 건물 42.65㎡',
       '서울특별시 성동구 성수동2가  램킨 증흥S-클래스 오피스텔대지 8.45㎡ 건물 42.65㎡',
       '서울특별시 성동구 성수동2가  램킨 증흥S-클래스 오피스텔임대보증금',
       '서울특별시 성동구 성수동2가  램킨 중흥S-클래스 오피스텔임대보증금',
       '서울특별시 성동구 옥수동  극동그린아파트 건물 114.32㎡',
       '서울특별시 성동구 하왕십리동  청계벽산아파트 건물 26.90㎡',
       '서울특별시 성동구 용답동 5-5번지 495.90㎡ 중 186.20㎡',
       '서울특별시 성동구 행당동  서울숲리버뷰자이 건물 84.95㎡',
       '서울특별시 성동구 응봉동  대림종합상가 건물 0.00㎡',
       '[소재지 오기정정]서울특별시 성동구 응봉동 대림종합상가대지 46,394.00㎡ 중 50.96㎡ 건물 81.41㎡',
       '서울특별시 성동구 응봉동  대림종합상가 건물 0.00㎡',
       '[소재지 오기정정]서울특별시 성동구 응봉동 대림종합상가대지 46,394.00㎡ 중 46.95㎡ 건물 74.99㎡',
       '서울특별시 성동구 응봉동  대림종합상가 건물 0.00㎡',
       '[소재지 오기정정]서울특별시 성동구 응봉동 대림종합상가대지 46,394.00㎡ 중 49.25㎡ 건물 78.66㎡',
       '서울특별시 성동구 응봉동 대림종합상가 3건 임대보증금',
       '서울특별시 성동구 옥수동 대림e편한세상 옥스파크힐스 건물84.64㎡',
       '서울특별시 성동구 성수동2가 대지 54.90㎡ 건물 34.43㎡', '서울특별시 성동구 성수동2가 임대보증금 증가',
       '서울특별시 성동구 행당동  행당동한진아파트 건물 114.62㎡',
       '서울특별시 성동구 행당동  무학빌딩 3층 건물 148.00㎡', '서울특별시 성동구 성수동1가 건물 59.40㎡',
       '서울특별시 성동구 옥수동 e편한세상 옥수 파크힐스 건물84.64㎡',
       '서울특별시 성동구 옥수동 이편한세상옥수파크힐스 건물84.64㎡ (건물 84.64㎡ 증가)',
       '서울특별시 성동구 금호동3가 두산아파트 건물 145.16㎡중 72.58㎡',
       '서울특별시 성동구 금호동3가  두산아파트 건물 72.58㎡',
       '서울특별시 성동구 옥수동 옥수파크힐스아파트 건물115.90㎡',
       '서울특별시 성동구 성수동1가 668-23번지 221.00㎡ 중49.11㎡',
       '서울특별시 성동구 옥수동  더 어울림 아파트 건물 84.69㎡',
       '서울특별시 성동구 사근동 건물 0.00㎡ (건물 19.11㎡감소)',
       '서울특별시 성동구 옥수동  옥수삼성아파트 건물 59.70㎡ (건물 59.70㎡증가)',
       '서울특별시 성동구 행당동 건물 33.00㎡', '서울특별시 성동구 금호동4가  대우아파트 건물 84.71㎡',
       '서울특별시 성동구 옥수동  한남하이츠아파트 건물 177.16㎡',
       '서울특별시 성동구 성수동2가  성수동아이파크 건물 84.98㎡',
       '서울특별시 성동구 행당동  행당한진타운 건물 84.00㎡', '서울특별시 성동구 행당동 행당한진타운 임대보증금',
       '서울특별시 성동구 옥수동  옥수어울림 건물 128.12㎡ 중64.06㎡',
       '서울특별시 성동구 옥수동  옥수어울림 건물 128.12㎡ 중64.06㎡',
       '서울특별시 성동구 옥수동 어울림더리버아파트 임대보증금 감소',
       '서울특별시 성동구 옥수동 어울림더리버아파트 임대보증금 감소',
       '서울특별시 성동구 금호동3가  두산아파트  건물 59.97㎡',
       '서울특별시 성동구 용답동 대지 6.91㎡건물 21.09㎡',
       '서울특별시 성동구 행당동  서울숲 리버뷰자이 건물 84.90㎡ (건물 84.90㎡증가)',
       '서울특별시 성동구 행당동  대림아파트 건물 84.87㎡', '서울특별시 성동구 행당동  한진타운 건물 114.62㎡',
       '서울특별시 성동구 행당동 한진타운 임대보증금', '서울특별시 성동구 홍익동 건물 6.00㎡',
       '서울특별시 성동구 옥수동  극동그린아파트 건물 102.00㎡',
       '서울특별시 성동구 하왕십리동  텐즈힐아파트 건물 129.34㎡중 64.67㎡',
       '서울특별시 성동구 하왕십리동  텐즈힐아파트 건물 129.34㎡중 64.67㎡',
       '서울특별시성동구행당동 행당대림아파트건물11,544.12㎡중114.94㎡',
       '서울특별시 성동구 옥수동 건물 106.00㎡',
       '서울특별시 성동구 금호동4가  브라운스톤 금호2차 건물 84.99㎡',
       '서울특별시 성동구금호동1가 벽산아파트건물 114.57㎡중 57.29㎡',
       '서울특별시 성동구금호동1가 벽산아파트건물 114.57㎡중 57.29㎡',
       '서울특별시성동구 상왕십리동 텐즈힐아파트건물 84.90㎡중 42.45㎡',
       '서울특별시 성동구행당동 행당한진타운건물 114.62㎡중 57.31㎡',
       '서울특별시성동구 상왕십리동 텐즈힐아파트건물 84.90㎡중 42.45㎡',
       '서울특별시 성동구행당동 행당한진타운건물 114.62㎡중 57.31㎡',
       '서울특별시 성동구행당동 대림아파트건물 59.00㎡중 34.40㎡',
       '서울특별시 성동구 행당동  대림아파트 건물 59.00㎡중 24.60㎡',
       '서울특별시 성동구 상왕십리동 텐즈힐아파트 임대보증금',
       '서울특별시 성동구 행당동 행당한진타운아파트 건물144.00㎡ 중 57.31㎡ (건물 지분면적14.69㎡ 감소)',
       '서울특별시 성동구 행당동 행당한진타운아파트 건물144.00㎡ 중 57.32㎡ (건물 지분면적14.68㎡ 감소)',
       '서울특별시 성동구 행당동 행당한진타운아파트 임대보증금 감소',
       '서울특별시 성동구 행당동 행당한진타운아파트 임대보증금 감소',
       '서울특별시 성동구 상왕십리동  텐즈힐 건물 127.44㎡ 중63.72㎡',
       '서울특별시 성동구 상왕십리동  텐즈힐 건물 127.44㎡ 중63.72㎡',
       '서울특별시 성동구 성수동1가  트리마제아파트 건물 84.51㎡',
       '서울특별시 성동구  용답동 대지 28.59㎡건물 57.96㎡', '서울특별시 성동구 용답동 임대보증금',
       '서울특별시 성동구 하왕십리동 왕십리자이아파트 건물59.99㎡',
       '서울특별시 성동구 하왕십리동 대지 178.00㎡중 39.55㎡건물375.42㎡ 중 82.59㎡',
       '서울특별시 성동구 하왕십리동 대지 178.00㎡중 59.30㎡건물375.42㎡ 중 127.65㎡',
       '서울특별시 성동구 하왕십리동 임대보증금', '서울특별시 성동구 하왕십리동 임대보증금',
       '서울특별시 성동구 하왕십리동  센트라스 건물 115.99㎡',
       '서울특별시 성동구 금호동2가 신금호파크자이아파트 건물114.98㎡ (건물 114.98㎡ 증가)',
       '서울특별시 성동구 행당동 대지 249.66㎡ 건물 306.00㎡',
       '서울특별시 성동구 사근동 대지 126.00㎡ 건물 252.07㎡',
       '서울특별시 성동구 금호동3가 대지 36.36㎡ 건물 50.78㎡',
       '서울특별시 성동구 금호동3가 대지 32.38㎡ 건물 50.41㎡',
       '서울특별시 성동구 금호동3가 삼성빌33차 임대보증금', '서울특별시 성동구 성수동2가 건물 129.30㎡',
       '서울특별시 성동구 성수동2가 건물 42.97㎡', '서울특별시 성동구 행당1동  삼부아파트 건물 84.09㎡',
       '서울특별시 성동구 성수동2가 건물 77.72㎡ 중 38.86㎡',
       '서울특별시 성동구 용답동 102-23번지 189.70㎡ 중 2.34㎡',
       '서울특별시 성동구 용답동 102-24번지 142.20㎡ 중 1.76㎡',
       '서울특별시 성동구 용답동 103-4번지 95.20㎡ 중 1.17㎡',
       '서울특별시 성동구 용답동 104-19번지 307.30㎡ 중 3.80㎡',
       '서울특별시 성동구 옥수동  래미안 옥수 리버젠 건물 59.25㎡',
       '서울특별시 성동구 마장동  금호어울림아파트 건물 0.00㎡(건물 84.00㎡ 감소)',
       '서울특별시 성동구 도선동  신한넥스텔 대지 2.56㎡ 건물19.63㎡',
       '서울특별시 성동구 도선동 신한넥스텔 임대보증금',
       '서울특별시 성동구 성수동2가  램킨 중흥S-클래스 오피스텔대지 8.45㎡ 건물 42.65㎡',
       '서울특별시 성동구 성수동2가  램킨 중흥S-클래스 오피스텔대지 8.45㎡ 건물 42.65㎡',
       '서울특별시 성동구 성수동2가  램킨 중흥S-클래스 오피스텔임대보증금',
       '서울특별시 성동구 성수동2가  램킨 증흥S-클래스 오피스텔임대보증금',
       '서울특별시 성동구 금호동2가  신금호파크자이 건물 59.98㎡',
       '서울특별시 성동구 옥수동 e편한세상 옥수파크힐스 건물0.00㎡ (건물 84.30㎡ 감소)',
       '서울특별시 성동구 옥수동 이편한세상옥수파크힐스 건물84.92㎡ (건물 84.92㎡ 증가)',
       '서울특별시 성동구 금호동2가 신금호파크자이 임대보증금',
       '서울특별시 성동구 성수동2가 건물 63.68㎡ (건물 63.68㎡증가)',
       '서울특별시 성동구 옥수동  극동그린아파트 건물 114.32㎡',
       '서울특별시 성동구 하왕십리동  청계벽산아파트 건물 26.90㎡',
       '서울특별시 성동구 용답동 5-5번지 0.00㎡ 중 0.00㎡ (총면적495.90㎡ 감소, 지분면적 186.20㎡ 감소)',
       '서울특별시 성동구 행당동 건물 26.40㎡ (건물 26.40㎡ 증가)',
       '서울특별시 성동구 행당동  서울숲리버뷰자이 건물 0.00㎡(건물 84.95㎡ 감소)',
       '서울특별시 성동구 행당동  서울숲리버뷰자이 건물 84.95㎡(건물 84.95㎡ 증가)',
       '서울특별시 성동구 응봉동  대림종합상가 대지 46,394.00㎡ 중49.25㎡ 건물 78.66㎡',
       '서울특별시 성동구 응봉동  대림종합상가 대지 46,394.00㎡ 중50.96㎡ 건물 81.41㎡',
       '서울특별시 성동구 응봉동  대림종합상가 대지 46,394.00㎡ 중46.95㎡ 건물 74.99㎡',
       '서울특별시 성동구 응봉동 대림종합상가 3건 임대보증금',
       '서울특별시 성동구 성수동2가 대지 1,002.30㎡ 중 216.62㎡건물 2,864.02㎡ 중 954.67㎡ (대지 지분면적 216.62㎡ 증가,건물 지분면적 954.67㎡ 증가)',
       '서울특별시 성동구 성수동2가 임대보증금 증가',
       '서울특별시 성동구 옥수동 대림e편한세상 옥스파크힐스 건물0.00㎡ (건물 84.64㎡ 감소)',
       '서울특별시 성동구 옥수동  옥수어울림아파트 건물 128.53㎡(건물 128.53㎡ 증가)',
       '서울특별시 성동구 성수동2가 대지 54.90㎡ 건물 34.43㎡', '서울특별시 성동구 성수동2가 임대보증금',
       '서울특별시 성동구 도선동 20번지 25.82㎡ (25.82㎡ 증가)',
       '서울특별시 성동구 행당동  행당동한진아파트 건물 57.31㎡(건물 57.31㎡ 감소)',
       '서울특별시 성동구 행당동  무학빌딩 3층 건물 148.00㎡',
       '서울특별시 성동구 행당동  행당동한진아파트 건물 114.62㎡중57.31㎡(건물 총면적 114.62㎡증가, 지분면적 57.31㎡증가)',
       '서울특별시 성동구 옥수동 e편한세상 옥수 파크힐스 건물84.64㎡',
       '서울특별시 성동구 성수동1가 건물 59.40㎡', '서울특별시 성동구 하왕십리동 왕십리뉴타운센트라스 건물84.98㎡',
       '서울 성동구 성수동1가 59.4㎡ 중 29.7㎡', '서울 성동구 성수동1가 59.4㎡ 중 29.7㎡',
       '서울 성동구 성수동1가 임대보증금 증가', '서울 성동구 성수동1가 임대보증금 증가',
       '서울 성동구 금호동1가 114.57㎡', '서울 성동구 응봉동 84.42㎡', '서울 성동구 행당동 29.43㎡',
       '서울 성동구 도선동 38.58㎡', '서울 성동구 행당동 오피스텔 임대보증금',
       '서울 성동구 도선동 오피스텔 임대보증금', '서울 성동구 사근동 단독주택 12㎡(12㎡ 증가)',
       '서울 성동구 금호동4가 아파트 84.838㎡', '서울 성동구 금호동3가 116.81㎡',
       '서울특별시 성동구 성수동1가 건물 164.86㎡', '서울특별시 성동구 행당동 건물 84.87㎡',
       '서울특별시 성동구 행당동 임대보증금 증가'], dtype=object)

In [77]:
highofficer_rich_2019 = highofficer_rich[highofficer_rich['years']==2019]
highofficer_rich_2019

       성명  years          현재가액
510   김병관   2019 276,363,061.0
648   김세연   2019  96,695,316.0
1487  박덕흠   2019  52,314,676.0
1684   박정   2019  28,783,850.0
4009  최교일   2019  25,513,895.0
...   ...    ...           ...
2178  신정식   2019    -229,761.0
4440  황창화   2019    -239,508.0
2417  오인철   2019    -513,595.0
1646  박원순   2019    -736,504.0
3943  진선미   2019  -1,386,971.0

[2292 rows x 3 columns]

In [78]:
q1 = highofficer_rich_2019['현재가액'].quantile(q = 0.2)
q2 = highofficer_rich_2019['현재가액'].quantile(q = 0.4)
q3 = highofficer_rich_2019['현재가액'].quantile(q = 0.6)
q4 = highofficer_rich_2019['현재가액'].quantile(q = 0.8)
q5 = highofficer_rich_2019['현재가액'].quantile(q = 1)

In [79]:
print(q1)
print(q2)
print(q3)
print(q4)
print(q5)

354410.0
726635.4000000001
1249377.1999999993
2103023.8
276363061.0

In [80]:
def q(x):
    if x > q4 and x <= q5:
        return '5분위'
    elif x > q3 and x <= q4:
        return '4분위'
    elif x > q2 and x <= q3:
        return '3분위'
    elif x > q1 and x <= q2:
        return '2분위'
    else:
        return '1분위'

In [81]:
quantile = highofficer_rich_2019['현재가액'].apply(q)
highofficer_rich_2019['분위'] = quantile
highofficer_rich_2019

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       성명  years          현재가액   분위
510   김병관   2019 276,363,061.0  5분위
648   김세연   2019  96,695,316.0  5분위
1487  박덕흠   2019  52,314,676.0  5분위
1684   박정   2019  28,783,850.0  5분위
4009  최교일   2019  25,513,895.0  5분위
...   ...    ...           ...  ...
2178  신정식   2019    -229,761.0  1분위
4440  황창화   2019    -239,508.0  1분위
2417  오인철   2019    -513,595.0  1분위
1646  박원순   2019    -736,504.0  1분위
3943  진선미   2019  -1,386,971.0  1분위

[2292 rows x 4 columns]

In [82]:
highofficer_rich_2019['분위_sh']=pd.qcut(highofficer_rich_2019['현재가액'],5,labels=["1","2","3","4","5"],duplicates='raise')
highofficer_rich_2019

C:\Users\sds\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

       성명  years          현재가액   분위 분위_sh
510   김병관   2019 276,363,061.0  5분위     5
648   김세연   2019  96,695,316.0  5분위     5
1487  박덕흠   2019  52,314,676.0  5분위     5
1684   박정   2019  28,783,850.0  5분위     5
4009  최교일   2019  25,513,895.0  5분위     5
...   ...    ...           ...  ...   ...
2178  신정식   2019    -229,761.0  1분위     1
4440  황창화   2019    -239,508.0  1분위     1
2417  오인철   2019    -513,595.0  1분위     1
1646  박원순   2019    -736,504.0  1분위     1
3943  진선미   2019  -1,386,971.0  1분위     1

[2292 rows x 5 columns]

In [83]:
a=pd.qcut(highofficer_rich_2019['현재가액'],5,labels=None,retbins=True,precision=0,duplicates='raise')
a

(510     (2103024.0, 276363061.0]
 648     (2103024.0, 276363061.0]
 1487    (2103024.0, 276363061.0]
 1684    (2103024.0, 276363061.0]
 4009    (2103024.0, 276363061.0]
                   ...
 2178      (-1386972.0, 354410.0]
 4440      (-1386972.0, 354410.0]
 2417      (-1386972.0, 354410.0]
 1646      (-1386972.0, 354410.0]
 3943      (-1386972.0, 354410.0]
 Name: 현재가액, Length: 2292, dtype: category
 Categories (5, interval[float64]): [(-1386972.0, 354410.0] < (354410.0, 726635.0] < (726635.0, 1249377.0] < (1249377.0, 2103024.0] < (2103024.0, 276363061.0]],
 array([-1.38697100e+06,  3.54410000e+05,  7.26635400e+05,  1.24937720e+06,
         2.10302380e+06,  2.76363061e+08]))

In [84]:
highofficer_merge = highofficer_2019.merge(highofficer_rich_2019, left_on = '성명', right_on = '성명')
highofficer_merge

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,증가액_실거래가,감소액,감소액_실거래가,현재가액_x,변동사유,years_x,years_y,현재가액_y,분위,분위_sh
0,42448,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,...,0.0,0.0,0.0,"23,913.0",공시지가 변동,2019,2019,"2,016,012.0",4분위,4
1,42449,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,...,0.0,0.0,0.0,"86,780.0",공시지가 변동,2019,2019,"2,016,012.0",4분위,4
2,42450,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,0.0,0.0,0.0,355.0,공시지가 변동,2019,2019,"2,016,012.0",4분위,4
3,42451,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,0.0,0.0,0.0,331.0,공시지가 변동,2019,2019,"2,016,012.0",4분위,4
4,42452,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,0.0,0.0,0.0,"1,113.0",공시지가 변동,2019,2019,"2,016,012.0",4분위,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37819,86146,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,토지,본인,임야,...,0.0,432.0,0.0,"3,142.0",가액변동,2019,2019,"-116,650.0",1분위,1
37820,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,0.0,0.0,0.0,"264,000.0",가액변동,2019,2019,"-116,650.0",1분위,1
37821,86148,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기,배우자,자동차,...,0.0,"1,560.0",0.0,"5,040.0",가액변동,2019,2019,"-116,650.0",1분위,1
37822,86149,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,본인,NaN,...,0.0,"30,513.0",0.0,"228,714.0","채무 상환, 저축연금 일부 지급받음",2019,2019,"-116,650.0",1분위,1
37823,86150,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,배우자,NaN,...,0.0,"2,377.0",0.0,"14,202.0","채무 상환, 저축연금 일부 지급받음",2019,2019,"-116,650.0",1분위,1

In [85]:
highofficer_asset = highofficer_merge.groupby(['분위_sh', '대분류'])['현재가액_x'].sum().reset_index()
highofficer_asset

   분위_sh             대분류        현재가액_x
0      1              건물 115,517,974.0
1      1     고지거부및등록제외사항           0.0
2      1         골동품및예술품     155,000.0
3      1            금및백금     140,467.0
4      1             보석류      85,000.0
..   ...             ...           ...
75     5              채권 116,365,088.0
76     5              토지 276,632,352.0
77     5  합명-합자-유한회사출자지분  10,314,205.0
78     5              현금   1,495,654.0
79     5             회원권  14,222,439.0

[80 rows x 3 columns]

In [86]:
highofficer_asset.to_excel('C:\\GitHub\\test\\highofficer_asset.xlsx')