In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [112]:
apt = pd.read_excel('C:\\GitHub\\test\\apt_transaction.xlsx')
rent = pd.read_excel('C:\\GitHub\\test\\apt_rent_transaction.xlsx')

In [113]:
apt.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3

In [114]:
rent.head()

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,24,"50,000",0,9,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,31,"48,000",0,1,1988,언주로 103
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,10,"55,000",0,8,1988,언주로 103
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,21,"65,000",0,2,1988,언주로 103
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,202002,5,"53,000",0,8,1988,언주로 103

In [115]:
apt_total = pd.concat([apt, rent], ignore_index = True)
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원)
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,NaN,NaN,NaN
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,NaN,NaN,NaN
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,NaN,NaN,NaN
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,NaN,NaN,NaN
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20

In [116]:
type = apt_total['전월세구분'].fillna('매매')
deposit = apt_total['보증금(만원)'].fillna(0)
rent = apt_total['월세(만원)'].fillna(0)

In [117]:
apt_total['전월세구분'] = type
apt_total['보증금(만원)'] = deposit
apt_total['월세(만원)'] = rent
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원)
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20

In [118]:
apt_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274912 entries, 0 to 274911
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   시군구       274912 non-null  object
 1   번지        274623 non-null  object
 2   본번        274912 non-null  int64
 3   부번        274912 non-null  int64
 4   단지명       274912 non-null  object
 5   전용면적(㎡)   274912 non-null  float64
 6   계약년월      274912 non-null  int64
 7   계약일       274912 non-null  int64
 8   거래금액(만원)  98563 non-null   object
 9   층         274912 non-null  int64
 10  건축년도      274912 non-null  int64
 11  도로명       274912 non-null  object
 12  전월세구분     274912 non-null  object
 13  보증금(만원)   274912 non-null  object
 14  월세(만원)    274912 non-null  object
dtypes: float64(1), int64(6), object(8)
memory usage: 31.5+ MB

In [119]:
apt_total['구단위']=apt_total['시군구'].astype(str).str.split(' ').str[0:2]
apt_total['동단위']=apt_total['시군구'].astype(str).str.split(' ').str[2]
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원),구단위,동단위
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0,"[서울특별시, 강남구]",개포동
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0,"[서울특별시, 강남구]",개포동
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0,"[서울특별시, 강남구]",개포동
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0,"[서울특별시, 강남구]",개포동
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0,"[서울특별시, 강남구]",개포동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0,"[서울특별시, 중랑구]",중화동
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0,"[서울특별시, 중랑구]",중화동
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,"[서울특별시, 중랑구]",중화동
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,"[서울특별시, 중랑구]",중화동
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20,"[서울특별시, 중랑구]",중화동