In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [151]:
apt = pd.read_excel('C:\\GitHub\\test\\apt_transaction.xlsx')
rent = pd.read_excel('C:\\GitHub\\test\\apt_rent_transaction.xlsx')

In [152]:
apt.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3

In [153]:
rent.head()

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,24,"50,000",0,9,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,31,"48,000",0,1,1988,언주로 103
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,10,"55,000",0,8,1988,언주로 103
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,21,"65,000",0,2,1988,언주로 103
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,202002,5,"53,000",0,8,1988,언주로 103

In [154]:
apt_total = pd.concat([apt, rent], ignore_index = True)
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원)
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,NaN,NaN,NaN
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,NaN,NaN,NaN
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,NaN,NaN,NaN
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,NaN,NaN,NaN
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20

In [155]:
type = apt_total['전월세구분'].fillna('매매')
deposit = apt_total['보증금(만원)'].fillna(0)
rent = apt_total['월세(만원)'].fillna(0)
pay = apt_total['거래금액(만원)'].fillna(0)

In [156]:
apt_total['전월세구분'] = type
apt_total['보증금(만원)'] = deposit
apt_total['월세(만원)'] = rent
apt_total['거래금액(만원)'] = pay
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원)
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,0,23,1998,동일로 752,전세,"34,000",0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,0,6,2003,동일로144길 74,전세,"28,000",0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,0,2,2003,동일로144길 74,월세,"10,000",30
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,0,2,2003,동일로144길 74,월세,"10,000",30
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,0,4,2007,봉화산로27가길 19,월세,"10,000",20

In [157]:
apt_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274912 entries, 0 to 274911
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   시군구       274912 non-null  object
 1   번지        274623 non-null  object
 2   본번        274912 non-null  int64
 3   부번        274912 non-null  int64
 4   단지명       274912 non-null  object
 5   전용면적(㎡)   274912 non-null  float64
 6   계약년월      274912 non-null  int64
 7   계약일       274912 non-null  int64
 8   거래금액(만원)  274912 non-null  object
 9   층         274912 non-null  int64
 10  건축년도      274912 non-null  int64
 11  도로명       274912 non-null  object
 12  전월세구분     274912 non-null  object
 13  보증금(만원)   274912 non-null  object
 14  월세(만원)    274912 non-null  object
dtypes: float64(1), int64(6), object(8)
memory usage: 31.5+ MB

In [173]:
apt_total['구단위']=apt_total['시군구'].astype(str).str.split(' ').str[1]
apt_total['동단위']=apt_total['시군구'].astype(str).str.split(' ').str[2]
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원),구단위,동단위,거래금액(만원)_re
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0,강남구,개포동,160000.0
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0,강남구,개포동,149500.0
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0,강남구,개포동,155000.0
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0,강남구,개포동,157000.0
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0,강남구,개포동,151500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0,중랑구,중화동,0.0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0,중랑구,중화동,0.0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,0.0
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,0.0
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20,중랑구,중화동,0.0

In [174]:
apt_total['거래금액(만원)'] = apt_total['거래금액(만원)'].str.strip()
apt_total['거래금액(만원)_re'] = apt_total['거래금액(만원)'].str.replace(',','')
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원),구단위,동단위,거래금액(만원)_re
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0,강남구,개포동,160000
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0,강남구,개포동,149500
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0,강남구,개포동,155000
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0,강남구,개포동,157000
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0,강남구,개포동,151500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0,중랑구,중화동,NaN
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0,중랑구,중화동,NaN
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,NaN
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,NaN
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20,중랑구,중화동,NaN

In [175]:
apt_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274912 entries, 0 to 274911
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   시군구          274912 non-null  object
 1   번지           274623 non-null  object
 2   본번           274912 non-null  int64
 3   부번           274912 non-null  int64
 4   단지명          274912 non-null  object
 5   전용면적(㎡)      274912 non-null  float64
 6   계약년월         274912 non-null  int64
 7   계약일          274912 non-null  int64
 8   거래금액(만원)     98563 non-null   object
 9   층            274912 non-null  int64
 10  건축년도         274912 non-null  int64
 11  도로명          274912 non-null  object
 12  전월세구분        274912 non-null  object
 13  보증금(만원)      274912 non-null  object
 14  월세(만원)       274912 non-null  object
 15  구단위          274912 non-null  object
 16  동단위          274912 non-null  object
 17  거래금액(만원)_re  98563 non-null   object
dtypes: float64(1), int64(6), object(11)
memory usage: 37.8+ MB

In [176]:
apt_total['거래금액(만원)_re'] = pd.to_numeric(apt_total['거래금액(만원)_re'])
apt_total['거래금액(만원)_re'].fillna(0, inplace = True)
apt_total

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,전월세구분,보증금(만원),월세(만원),구단위,동단위,거래금액(만원)_re
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,201911,18,"160,000",2,1988,언주로 103,매매,0,0,강남구,개포동,160000.0
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202006,23,"149,500",4,1988,언주로 103,매매,0,0,강남구,개포동,149500.0
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201908,28,"155,000",4,1987,언주로 3,매매,0,0,강남구,개포동,155000.0
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3,매매,0,0,강남구,개포동,157000.0
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3,매매,0,0,강남구,개포동,151500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274907,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,202007,11,NaN,23,1998,동일로 752,전세,"34,000",0,중랑구,중화동,0.0
274908,서울특별시 중랑구 중화동,274-76,274,76,한영(103),87.31,201910,22,NaN,6,2003,동일로144길 74,전세,"28,000",0,중랑구,중화동,0.0
274909,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,0.0
274910,서울특별시 중랑구 중화동,274-77,274,77,한영(104),67.57,201909,25,NaN,2,2003,동일로144길 74,월세,"10,000",30,중랑구,중화동,0.0
274911,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201909,24,NaN,4,2007,봉화산로27가길 19,월세,"10,000",20,중랑구,중화동,0.0

In [177]:
apt_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274912 entries, 0 to 274911
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   시군구          274912 non-null  object
 1   번지           274623 non-null  object
 2   본번           274912 non-null  int64
 3   부번           274912 non-null  int64
 4   단지명          274912 non-null  object
 5   전용면적(㎡)      274912 non-null  float64
 6   계약년월         274912 non-null  int64
 7   계약일          274912 non-null  int64
 8   거래금액(만원)     98563 non-null   object
 9   층            274912 non-null  int64
 10  건축년도         274912 non-null  int64
 11  도로명          274912 non-null  object
 12  전월세구분        274912 non-null  object
 13  보증금(만원)      274912 non-null  object
 14  월세(만원)       274912 non-null  object
 15  구단위          274912 non-null  object
 16  동단위          274912 non-null  object
 17  거래금액(만원)_re  274912 non-null  float64
dtypes: float64(2), int64(6), object(10)
memory usage: 37.8+ MB

In [186]:
apt_total_buy = apt_total[apt_total['전월세구분'] == '매매']
apt_monthly = apt_total_buy.groupby(['구단위', '계약년월'])['거래금액(만원)_re'].mean().reset_index()
apt_monthly

     구단위    계약년월    거래금액(만원)_re
0    강남구  201908  183086.887052
1    강남구  201909  186896.147705
2    강남구  201910  187130.542857
3    강남구  201911  183953.401887
4    강남구  201912  171788.696809
..   ...     ...            ...
295  중랑구  202003   49005.797101
296  중랑구  202004   44843.014706
297  중랑구  202005   44522.747748
298  중랑구  202006   51868.063830
299  중랑구  202007   52363.554007

[300 rows x 3 columns]

In [187]:
apt_monthly.to_excel('C:\\GitHub\\test\\apt_monthly.xlsx')

In [188]:
apt_monthly_pivot = apt_monthly.pivot_table(
index = '구단위',
columns = '계약년월',
values = '거래금액(만원)_re',
dropna = False)

apt_monthly_pivot

계약년월,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007
구단위,,,,,,,,,,,,
강남구,183086.887052,186896.147705,187130.542857,183953.401887,171788.696809,154908.846154,161472.139241,170534.074074,195356.206897,183647.927632,181286.277494,161628.018315
강동구,76337.146597,77289.740385,73700.665295,77393.282443,71374.539877,65284.520958,69655.682741,63168.181818,65597.656250,70120.537975,87281.040462,87105.307018
강북구,44995.703125,44189.338235,48961.024390,51210.994764,50455.060729,46467.603834,51212.213740,53343.167702,49934.848485,51229.090909,59941.935484,59727.248677
강서구,59025.217391,61646.472393,63580.475382,65290.759931,62765.460030,62532.440758,61398.246187,57556.801619,54886.182796,62302.153846,66325.621886,67378.180693
관악구,54053.058252,55435.492228,56105.982036,58210.900000,57172.614841,57154.978723,57773.491525,56261.179775,55616.115108,56000.602410,65948.797595,57449.463768
광진구,92201.675127,95700.536913,99289.197324,97381.004444,99855.681818,93384.126984,90712.173913,93927.884615,81679.487179,92418.181818,106190.000000,107873.584906
구로구,54625.263158,51900.000000,54844.128015,56288.765217,53108.246063,50933.623025,50332.526132,48821.488673,46620.217391,49712.402235,58114.787356,60449.918534
금천구,44061.843972,43595.177143,47142.390244,46730.512821,44284.962406,47821.480000,45375.945946,36773.750000,41611.132075,45225.000000,48518.260870,49665.644172
노원구,45705.457627,46019.713405,46052.257778,47810.495085,43256.025024,46437.955936,45900.735931,46298.256000,45715.322581,47738.948220,50340.559723,55178.274559
도봉구,39251.233051,41836.210332,42146.968974,44413.611111,43606.190476,44022.343324,43722.291297,40902.240260,40210.500000,40677.544484,42434.119718,46492.350674
동대문구,61447.735192,63025.540541,61006.806283,61149.124726,58620.546697,60782.482517,62344.852941,58128.430233,60314.885246,62730.000000,72881.638418,70235.287356
동작구,87385.433790,84491.398305,87824.400000,88828.393881,88963.183280,81955.365854,87603.945652,82646.153846,83128.000000,86810.135135,93929.850187,100473.575130
마포구,93977.303754,92063.414634,97214.823529,95967.565056,95678.502660,89500.769231,89186.298077,90146.875000,84479.523810,92346.875000,103078.726899,93386.284289
서대문구,71599.668874,70511.250000,64830.244604,74773.373494,72646.617647,65414.410480,67886.029412,66297.608696,67007.954545,71103.703704,78667.817623,80797.416413
서초구,174143.164557,179818.867925,167730.424628,165594.631702,160326.516129,130294.583333,146788.920455,141983.324561,175845.744681,179802.202899,171160.147940,175420.303951
성동구,93875.368732,93380.033557,100531.509091,97828.768939,102110.328638,93011.796117,99394.190141,105046.278146,103378.289474,103576.875000,110199.844961,118398.637771
성북구,59280.569307,59420.976431,59508.918033,60732.658023,60575.094937,58110.067114,62704.354528,62175.798319,59716.511628,62275.691700,68911.026253,72843.902240
송파구,114394.005168,118971.034976,121089.336143,125755.701603,120123.739407,103264.590909,119565.124654,112310.068493,122645.948905,140016.144928,132222.387597,116687.440092
양천구,78555.154639,83931.887755,88765.422297,87590.841429,79146.457766,68753.891213,68002.025723,66220.838323,78099.043478,83471.639676,90790.427099,91163.315217
영등포구,74810.873288,83064.873646,81971.677704,82619.802632,78141.905312,74857.516340,79966.666667,79559.520548,77316.115702,87038.085106,93524.519393,88691.559633
용산구,157639.230159,145376.673913,154222.859813,150656.766055,131530.716867,123660.376238,138880.587500,122145.918919,141035.483871,149547.206349,161980.988417,137125.367647
은평구,51781.772152,50017.637209,56106.956647,55006.942708,59257.206490,56470.576923,55645.409605,55069.408867,48594.000000,57833.278970,64031.527273,67125.353075
종로구,75372.321429,94758.301887,91485.375000,82429.186047,84162.317073,65872.857143,68571.578947,69135.500000,66676.000000,79608.867925,90922.972973,87503.095238
중구,81202.054795,87497.560976,80641.570513,84676.397516,80143.235294,83436.867470,86753.901099,76315.833333,83017.142857,86844.444444,90422.469136,93452.155172
중랑구,47034.110169,46378.451883,47185.169231,48370.411985,39134.465116,46616.455696,48262.307692,49005.797101,44843.014706,44522.747748,51868.063830,52363.554007

In [190]:
apt_monthly_pivot.to_excel('C:\\GitHub\\test\\apt_monthly_pivot.xlsx')